DirectoryPath: "dist"
EnforceHTTPS: true
IgnoreEmptyHref: true
IgnoreInternalEmptyHash: true
IgnoreDirectoryMissingTrailingSlash: false
IgnoreURLs:
  - "viam.setup"
  - "orangepi.org"
  - "rtk2go.com"
IgnoreDirs:
  - "lib"
CacheExpires: "6h"
# IgnoreDirs: - if we need to ever ignore files
CheckExternal: false