DirectoryPath: "dist"
EnforceHTTPS: true
IgnoreEmptyHref: true
IgnoreInternalEmptyHash: true
IgnoreDirectoryMissingTrailingSlash: true
IgnoreURLs:
- "example.com"
- "^/misc/js/script.js$"
- "linkedin.com"
- "app.viam.com"
- "beaglebone.local"
- "instagram.com"
- "twitter.com"
- "github.com/viamrobotics/"
- "openai.com"
- "espressif.com"
- "pinout.xyz"
- "play.google.com"
- "packages.viam.com" #IgnoreHTTPS does not work on staging
IgnoreDirs:
- "lib"
CacheExpires: "6h"
