DirectoryPath: "dist"
EnforceHTTPS: true
IgnoreEmptyHref: true
IgnoreInternalEmptyHash: true
IgnoreDirectoryMissingTrailingSlash: false
# rate limiting settings
MaxConcurrency: 1
RequestDelay: 1000ms
Timeout: 30s
IgnoreURLs:
  - "example.com"
  - "^/misc/js/script.js$"
  - "linkedin.com"
  - "app.viam.com"
  - "beaglebone.local"
  - "instagram.com"
  - "twitter.com"
  - "github.com/viamrobotics/docs"
  - "openai.com"
  - "espressif.com"
  - "pinout.xyz"
  - "play.google.com"
  - "scuttlerobot.org"
  - "numato.com"
  - "nvidia.com"
  - "slamtec.com"
  - "universal-robots.com"
  - "digikey.com"
  - "ufactory.cc"
  - "medium.com"
  - "radxa.com"
  - "electronics-tutorials.ws"
  - "marketplace.visualstudio.com"
  - "chrome.google.com"
  - "raspberrypi.com"
  - "grabcad.com"
  - "orangepi.org"
  - "rtk2go.com"
  - "researchgate.net"
  - "trinamic.com"
  - "viam.setup"
  - "web.archive"
  - "elevenlabs.io"
  - "docs.m5stack.com"
  - "code.visualstudio.com"
  - "thingiverse.com"
  - "unsplash.com"
  - "docs.github.com"
  - "bugs.launchpad.net"
  - "grpc.io"
  - "odroid.com"
  - "viamapplications.com"
IgnoreDirs:
  - "lib"
CacheExpires: "6h"
# IgnoreDirs: - if we need to ever ignore files
