# Default state for all rules
default: true

options:
  frontMatter: true

#/no-hard-tabs - Hard tabs
MD010:
  spaces_per_tab: 4

# MD013/line-length - Line length
MD013: false

# MD024/no-duplicate-heading/no-duplicate-header - Multiple headings with the same content
MD024:
  # Only check sibling headings
  siblings_only: true

# List numbering
MD029: false

# MD033/no-inline-html - Inline HTML
MD033: false

