extends: existence
message: "You can remove most adverbs. Use your best judgment."
link: 'https://github.com/rackerlabs/docs-style-guide/blob/master/style-guide/writing/write-clear-concise-sentences-paragraphs.rst'
level: suggestion
ignorecase: true
scope: sentence
nonword: false
tokens:
  - '\b(\w+ly)'