extends: existence
message: "You can remove most adverbs. Use your best judgment."
link: 'https://docs.rackspace.com/docs/style-guide/writing/write-clear-concise-sentences-paragraphs/'
level: suggestion
ignorecase: true
scope: sentence
nonword: false
tokens:
  - '\b(\w+ly)'