extends: existence
message: "Avoid the subjuntive '%s'."
link: 'https://github.com/rackerlabs/docs-style-guide/blob/master/style-guide/writing/write-to-the-user.rst'
ignorecase: true
level: warning
scope: sentence
nonword: true
tokens:
  - '\bwould\b'
  - '\ncould\b'
  - '\bshould\b'
