extends: existence
message: "Don't use '%s'."
link: 'https://github.com/rackerlabs/docs-style-guide/blob/master/style-guide/terminology/alphabetical-terms.rst'
ignorecase: true
level: warning
tokens:
  - abortion
  - and/or
  - slash mark
  - billion
  - biweekly
  - bimonthly
  - front end
  - front-end
  - if necessary
  - respectively
  - trillion
