extends: existence
message: "Avoid the subjuntive '%s'."
link: 'https://docs.rackspace.com/docs/style-guide/writing/write-to-the-user/'
ignorecase: true
level: warning
scope: sentence
nonword: true
tokens:
  - '\bwould\b'
  - '\ncould\b'
  - '\bshould\b'
