extends: substitution
message: "Consider if '%s' makes sense instead of '%s'."
link: 'https://docs.google.com/document/d/1-SAcVPWcZHM1Na88d0_k5HVmc3tRtRHgmrXzKD3uF2I/edit'
level: warning
ignorecase: true
action:
  name: replace
swap:
  viam app: Viam app
  Viam App: Viam app
  viam registry: Viam Registry
  Viam registry: Viam Registry
  viam agent: Viam Agent
  Viam agent: Viam Agent
  viam cloud: Viam Cloud
  Viam cloud: Viam Cloud
  RPLIDAR: RPlidar
  Rplidar: RPlidar
  Viam platform: Viam platform
  Scuttle robot: SCUTTLE robot
  Scuttle Robot: SCUTTLE robot
  Viam-server: viam-server
  Viam server: viam-server
  Viam-Server: viam-server
  Config Tab: CONFIG tab
  Config tab: CONFIG tab
  Vision service: vision service
  Vision Service: vision service
  Motion service: motion service
  Motion Service: motion service
  slam service: SLAM service
  Slam service: SLAM service
  SLAM Service: SLAM service
  Data Management Service: data management service
  Data Management service: data management service
