extends: existence
message: "Verify your usage of '%s' with the Alphabetical List of Terms in the style guide."
link: 'https://docs.google.com/document/d/1-SAcVPWcZHM1Na88d0_k5HVmc3tRtRHgmrXzKD3uF2I/edit'
level: suggestion
ignorecase: true
tokens:
  - member
  - user
  - sub-part
  - remote