# Based on: https://github.com/errata-ai/Google/blob/master/Google/Colons.yml
extends: existence
message: "Consider splitting this into two sentences. If you cannot '%s' should be in lowercase."
link: 's://docs.rackspace.com/docs/style-guide/style/punctuation#colons'
nonword: true
level: warning
scope: heading
tokens:
  - ':\s[A-Z]'