extends: existence
message: "When a comma is required after a quotation that’s embedded in text, place the comma inside the closing quotation mark."
link: 'https://github.com/rackerlabs/docs-style-guide/blob/master/style-guide/style/punctuation#commas.rst'
level: error
scope: text
nonword: true
tokens:
  - '(“\w*”),'
  - '("\w*"),'
  - '["“][^"”“]+["”][.,]'
  - '"[^"]+"[.,?]'