extends: existence
message: "To refer to product releases, use earlier or later."
link: 'https://github.com/rackerlabs/docs-style-guide/blob/master/style-guide/terminology/general-term-guidelines/use-consistent-time-references.rst'
nonword: false
level: suggestion
tokens:
  - '(SDK \d.\d.* (higher|lower|above|below|older|newer))'
  - '((higher|lower|above|below|older|newer).*SDK \d.\d)'
