extends: substitution
message: "Feel free to use '%s' instead of '%s'."
link: 'https://github.com/rackerlabs/docs-style-guide/blob/master/style-guide/style/contractions.rst'
level: suggestion
ignorecase: true
action:
  name: replace
swap:
  it is: it's
  that is: that's
  there is: there's
  they are: they're
  you are: you're
  that is: that's
  we are: we're
  we have: we've
