extends: existence
message: "Use a comma before and after the year '%s' when the month, day, and year are embedded in a sentence."
link: 'https://github.com/rackerlabs/docs-style-guide/blob/master/style-guide/style/dates.rst'
ignorecase: true
level: error
nonword: true
tokens:
  - '(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)|May|Jun(?:e)|Jul(?:y)|Aug(?:ust)|Sep(?:tember)?|Oct(?:ober)|Nov(?:ember)?|Dec(?:ember)?) \d{1,2} \d{4}[^,|\.|)]'
  - '(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)|May|Jun(?:e)|Jul(?:y)|Aug(?:ust)|Sep(?:tember)?|Oct(?:ober)|Nov(?:ember)?|Dec(?:ember)?) \d{1,2}, \d{4}[^,|\.|)]'
