extends: existence
message: "Spell out all ordinal numbers ('%s'). For example, don’t use January 1st; use January 1 instead."
link: 'https://docs.rackspace.com/docs/style-guide/style/dates'
level: error
nonword: true
tokens:
  - \d+(?:st|nd|rd|th)