extends: conditional
message: "Use *.example.com or *.example.org in example domain names
instead of '%s'."
link: 'https://github.com/rackerlabs/docs-style-guide/blob/master/style-guide/style/email-addresses.rst'
level: suggestion
ignorecase: false
# This is a hack to allow us to make use of exceptions.
first: '(\b((http|https|srv)://)?\w+(\.\w+)+)'
second: '(\b((http|https|srv)://)?\w+(\.\w+)+)'
# ... with the exception of these:
exceptions:
  - '(\b.*.example.(com|net|org))'
  - '(\b.*.example\s)'
  - '(\b.*.?viam.*\b)'