extends: existence
message: "Use an ellipsis (…) only in syntax or to indicate omitted code in code examples."
link: 's://docs.rackspace.com/docs/style-guide/style/punctuation#ellipses'
nonword: true
level: warning
action:
  name: remove
tokens:
  - '\.\.\.'