extends: conditional
message: "Use @example.com or @example.org as the domain name for example
email addresses instead of '%s'."
link: 'https://github.com/rackerlabs/docs-style-guide/blob/master/style-guide/style/email-addresses.rst'
level: suggestion
ignorecase: false
# This is a hack to allow us to make use of exceptions.
first: '@\w*\.\w*\b'
second: '@\w*\.\w*\b'
# ... with the exception of these:
exceptions:
  - '@example.com'
  - '@example.org'