extends: substitution
message: "Use '%s' instead of the metaphor '%s'."
link: 'https://github.com/rackerlabs/docs-style-guide/blob/master/style-guide/terminology/terms-for-global-audience#avoid-metaphorical-terms.rst'
level: suggestion
ignorecase: true
action:
  name: replace
swap:
  a handful of: a few
  table a discussion: postpone a discussion
  vanilla: standard
  pitfalls: problems
  the drawback: the disadvantage
  jump: start

