extends: existence
message: "Usually words with the prefix self- ('%s') are hyphenated"
link: https://docs.rackspace.com/docs/style-guide/terminology/alphabetical-terms
ignorecase: true
level: error
action:
  name: convert
  params:
    - simple
tokens:
  - 'self\w+'
