extends: existence
message: "IPv4 addresses should use periods (.) as separators ('%s')."
link: 'https://github.com/rackerlabs/docs-style-guide/blob/master/style-guide/style/ip-addresses.rst'
level: error
nonword: true
tokens:
  - '((((\d{1,3}:){3})(\d{1,3}))(/\d+)?)'