extends: existence
message: "IPv6 addresses should use colons (:) as separators ('%s')."
link: 'https://docs.rackspace.com/docs/style-guide/style/ip-addresses'
level: error
nonword: true
tokens:
  - '(((([[:xdigit:]]{4}(\.|:)){7})([[:xdigit:]]{4}){1})(/\d+)?)'