extends: substitution
message: "Use '%s' instead of the negative word '%s'."
link: 'https://docs.rackspace.com/docs/style-guide/writing/use-positive-statements'
level: warning
ignorecase: true
action:
  name: replace
swap:
  damage: affect
  catastrophic: serious
  bad: Use serious or add an explanation
  fail: unable to
  kill: cancel
  fatal: serious
  destroy: remove, delete
  wrong: incorrect, inconsistent