extends: existence
message: "Spell out numbers like '%s' from zero through nine unless the numers are
as displayed or need to be input, are followed by a unit, or indicate
dimensions or time."
link: 'https://docs.rackspace.com/docs/style-guide/style/numbers'
ignorecase: true
scope: sentence
level: suggestion
nonword: true
tokens:
  - ' \d{1} '
