extends: existence
message: "Don’t use the word inclusive in your description ('%s')."
link: 'https://github.com/rackerlabs/docs-style-guide/blob/master/style-guide/style/numbers.rst'
ignorecase: true
level: warning
nonword: true
tokens:
  - 'through .*, inclusive'
