extends: existence
message: "Avoid using semicolons, which are often misused and, even when used correctly, can make sentences longer and more difficult to understand."
link: 'https://github.com/rackerlabs/docs-style-guide/blob/master/style-guide/writing/use-correct-punctuation.rst'
nonword: true
level: suggestion
tokens:
  - ';'