extends: occurrence
message: "Try to keep sentences short (< 25 words)."
link: 'https://github.com/rackerlabs/docs-style-guide/blob/master/style-guide/writing/write-clear-concise-sentences-paragraphs.rst'
scope: sentence
level: suggestion
max: 25
token: '\b(\w+)\b'
