# Based on https://github.com/errata-ai/Google/blob/master/Google/Gender.yml
extends: existence
message: "Use singular they instead of '%s'."
level: warning
link: "https://docs.rackspace.com/docs/style-guide/writing/use-gender-neutral-pronouns"
ignorecase: true
tokens:
  - he/she
  - s/he
  - \(s\)he