# Based on: https://github.com/errata-ai/Google/blob/master/Google/Units.yml

extends: existence
message: "Use the correct case for '%s'."
nonword: true
ignorecase: false
level: error
tokens:
  - \d+v\b
