// Command gen-mcp-docs reads viamrobotics/app's mcpserver package and writes a Markdown table of
// its registered MCP tools, so the docs site's MCP server reference stays pegged to the server's
// actual tool registrations instead of to a hand-maintained list that can drift.
//
// It only parses source (go/parser, no go/types or go/packages), deliberately: a full type-check
// would need the rest of the app module to compile, including protobuf packages generated by a
// Docker-based buf step that isn't checked into the repo. Name, description, and category are all
// resolvable from plain syntax, including the handful of descriptions that interpolate a constant
// from another package in the same module (e.g. a timeout in seconds) -- resolving those means
// parsing that one sibling package too, but still never means compiling it.
package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// appModule is the Go module path of viamrobotics/app. A cross-package identifier is only
// followed when its import lives under this prefix -- an external dependency is never read, both
// because it's out of scope for tool metadata and because it could be large or unvendored.
const appModule = "github.com/viamrobotics/app"

// tool is one MCP tool as registered in mcpserver, ready to render as a table row.
type tool struct {
	Name        string
	Description string
	Category    string
}

const (
	categoryReadOnly        = "Read-only"
	categoryLiveMachineRead = "Live machine (read-only)"
	categoryWrite           = "Write"
	categoryDestroy         = "Write (destructive)"
	categoryLiveMachine     = "Live machine (destructive)"
)

// categoryOrder controls both grouping and sort priority in the output table. Both read-only
// categories come first, grouped together rather than split by whether they touch a live machine
// or just Viam's data layer: MCP clients (Claude included) gate confirmation on ReadOnlyHint alone,
// so that's the distinction that matters most to a reader deciding what needs review. Increasingly
// consequential write tools follow, then the tools that change or act on a live machine.
var categoryOrder = map[string]int{
	categoryReadOnly:        0,
	categoryLiveMachineRead: 1,
	categoryWrite:           2,
	categoryDestroy:         3,
	categoryLiveMachine:     4,
}

func main() {
	mcpserverDir := flag.String("mcpserver-dir", "", "path to viamrobotics/app's mcpserver/ directory")
	appDir := flag.String("app-dir", "", "path to the viamrobotics/app checkout root (defaults to the parent of -mcpserver-dir)")
	out := flag.String("out", "", "output path for the generated Markdown table")
	flag.Parse()
	if *mcpserverDir == "" || *out == "" {
		fmt.Fprintln(os.Stderr, "usage: gen-mcp-docs --mcpserver-dir=<path to viamrobotics/app/mcpserver> --out=<output .md path> [--app-dir=<path>]")
		os.Exit(2)
	}
	if *appDir == "" {
		*appDir = filepath.Dir(*mcpserverDir)
	}

	tools, err := extractTools(*mcpserverDir, *appDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-mcp-docs: %v\n", err)
		os.Exit(1)
	}

	if err := writeTable(*out, tools); err != nil {
		fmt.Fprintf(os.Stderr, "gen-mcp-docs: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("gen-mcp-docs: wrote %d tools to %s\n", len(tools), *out)
}

// extractTools parses every non-test .go file in mcpserverDir and returns the tools registered
// there, sorted by category then name so the output is stable across runs regardless of source
// order.
func extractTools(mcpserverDir, appDir string) ([]tool, error) {
	r := &resolver{appRoot: appDir, cache: map[string]*pkgInfo{}}
	pkg, err := r.packageAt(mcpserverDir)
	if err != nil {
		return nil, err
	}

	var tools []tool
	var walkErr error
	for _, f := range pkg.files {
		ast.Inspect(f, func(n ast.Node) bool {
			if walkErr != nil {
				return false
			}
			call, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}
			fn, ok := call.Fun.(*ast.Ident)
			if !ok || fn.Name != "addTool" {
				return true
			}
			// addTool[In, Out any](s *Server, tool *mcp.Tool, timeout time.Duration, h handlerFunc[In, Out]).
			// A call with any other arity means the registration convention this script relies on has
			// changed shape, and that's exactly the case that should stop the run rather than silently
			// mis-parse.
			if len(call.Args) != 4 {
				walkErr = fmt.Errorf("%s: addTool call has %d arguments, expected 4 -- the registration "+
					"convention this script relies on may have changed", pkg.fset.Position(call.Pos()), len(call.Args))
				return false
			}
			t, err := extractTool(r, scope{pkg: pkg, file: f}, call.Args[1])
			if err != nil {
				walkErr = fmt.Errorf("%s: %w", pkg.fset.Position(call.Pos()), err)
				return false
			}
			tools = append(tools, *t)
			return true
		})
	}
	if walkErr != nil {
		return nil, walkErr
	}
	if len(tools) == 0 {
		return nil, fmt.Errorf("found no tools in %s -- check whether the addTool/readOnlyTool/machineReadTool/writeTool/"+
			"machineTool registration convention this script relies on still holds", mcpserverDir)
	}

	sort.SliceStable(tools, func(i, j int) bool {
		if categoryOrder[tools[i].Category] != categoryOrder[tools[j].Category] {
			return categoryOrder[tools[i].Category] < categoryOrder[tools[j].Category]
		}
		return tools[i].Name < tools[j].Name
	})
	return tools, nil
}

// extractTool reads one addTool call's second argument -- the readOnlyTool/machineReadTool/writeTool/machineTool
// call that builds the *mcp.Tool -- and resolves it to a tool. sc is the scope of the file the
// addTool call itself appears in, which is where readOnlyTool/machineReadTool/writeTool/machineTool's own
// arguments must be resolved from. An unrecognized constructor is a hard error rather than a skip:
// silently dropping an unrecognized tool would produce a doc page that looks complete while
// quietly missing entries, which is worse than failing the run.
func extractTool(r *resolver, sc scope, arg ast.Expr) (*tool, error) {
	call, ok := arg.(*ast.CallExpr)
	if !ok {
		return nil, fmt.Errorf("expected a tool-constructor call (readOnlyTool/machineReadTool/writeTool/machineTool), got %T", arg)
	}
	fn, ok := call.Fun.(*ast.Ident)
	if !ok {
		return nil, fmt.Errorf("expected a tool-constructor call, got %T", call.Fun)
	}

	var category string
	var wantArgs int
	switch fn.Name {
	case "readOnlyTool":
		category, wantArgs = categoryReadOnly, 3
	case "machineReadTool":
		category, wantArgs = categoryLiveMachineRead, 3
	case "writeTool":
		category, wantArgs = categoryWrite, 4
	case "machineTool":
		category, wantArgs = categoryLiveMachine, 3
	default:
		return nil, fmt.Errorf("unrecognized tool constructor %q -- this script only knows readOnlyTool, "+
			"machineReadTool, writeTool, and machineTool; teach it the new constructor before trusting this output", fn.Name)
	}
	if len(call.Args) != wantArgs {
		return nil, fmt.Errorf("%s call has %d arguments, expected %d -- its signature may have changed",
			fn.Name, len(call.Args), wantArgs)
	}

	name, err := r.resolveString(call.Args[0], sc, map[string]bool{})
	if err != nil {
		return nil, fmt.Errorf("resolving %s name: %w", fn.Name, err)
	}
	description, err := r.resolveString(call.Args[2], sc, map[string]bool{})
	if err != nil {
		return nil, fmt.Errorf("resolving %s description for %q: %w", fn.Name, name, err)
	}

	if fn.Name == "writeTool" {
		destructive, err := resolveBool(call.Args[3])
		if err != nil {
			return nil, fmt.Errorf("resolving destructive flag for %q: %w", name, err)
		}
		if destructive {
			category = categoryDestroy
		}
	}

	return &tool{Name: name, Description: description, Category: category}, nil
}

// constDecl is a package-level const/var declaration together with the file that declares it.
// Tracking the file matters because a description's own expression may itself reference another
// package (see scope): that reference has to resolve through the import block of the file that
// wrote it, not through some blended view of every file in the package.
type constDecl struct {
	expr ast.Expr
	file *ast.File
}

// pkgInfo is one parsed package: its files (for the tool walk, only meaningful for mcpserver
// itself), its top-level const/var declarations, and each file's own import aliases -- everything
// a cross-package constant reference needs to resolve, without type-checking anything.
type pkgInfo struct {
	fset        *token.FileSet
	files       []*ast.File
	consts      map[string]constDecl
	fileImports map[*ast.File]map[string]string // per file: local alias -> import path
}

// scope is the package and specific file an expression is being resolved relative to. Go import
// aliases are scoped per file, not per package, so which file an expression came from is part of
// its meaning: two files in the same package are free to use the same alias for two different
// imports, and mcpserver's own files already do (both github.com/robfig/cron/v3 and
// github.com/Masterminds/semver/v3 are aliased "v3" by different files, from Go's default-to-last-
// path-segment rule). A single package-wide alias table would silently pick whichever file's import
// happened to be inserted last for any alias used in more than one file -- fine while neither
// collision target is an internal package this script would follow, but a silent wrong answer
// waiting to happen the day two files alias two different app/* packages the same way.
type scope struct {
	pkg  *pkgInfo
	file *ast.File
}

// resolver lazily parses and caches packages under appRoot as cross-package references need them.
type resolver struct {
	appRoot string
	cache   map[string]*pkgInfo
}

func (r *resolver) packageAt(dir string) (*pkgInfo, error) {
	if p, ok := r.cache[dir]; ok {
		return p, nil
	}

	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("reading %s: %w", dir, err)
	}
	// Every package this resolver touches is parsed in full, not just for its imports: a
	// cross-package lookup needs the target's top-level const/var declarations too (buildConstTable
	// only sees what's actually parsed), and the resolver only ever visits a handful of packages --
	// mcpserver plus whichever siblings its descriptions actually reference -- so there's no whole-
	// module cost to control for here.
	fset := token.NewFileSet()
	var files []*ast.File
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		f, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, 0)
		if err != nil {
			return nil, fmt.Errorf("parsing %s: %w", name, err)
		}
		files = append(files, f)
	}
	if len(files) == 0 {
		return nil, fmt.Errorf("no .go files found in %s", dir)
	}

	fileImports := map[*ast.File]map[string]string{}
	for _, f := range files {
		fileImports[f] = buildImportTable(f)
	}

	p := &pkgInfo{
		fset:        fset,
		files:       files,
		consts:      buildConstTable(files),
		fileImports: fileImports,
	}
	r.cache[dir] = p
	return p, nil
}

// resolveCrossPackage follows a pkg.Name reference to the declaring expression (and the scope it
// must itself be resolved in) in that package. Only an internal github.com/viamrobotics/app/*
// import is followed; anything else is a clear, immediate error rather than an attempt to fetch or
// vendor a third-party module. The alias is looked up in sc.file's own imports specifically -- see
// the scope doc comment for why that has to be per file rather than per package.
func (r *resolver) resolveCrossPackage(sel *ast.SelectorExpr, sc scope) (ast.Expr, scope, error) {
	alias, ok := sel.X.(*ast.Ident)
	if !ok {
		return nil, scope{}, fmt.Errorf("unsupported selector expression %T.%s", sel.X, sel.Sel.Name)
	}
	importPath, ok := sc.pkg.fileImports[sc.file][alias.Name]
	if !ok {
		return nil, scope{}, fmt.Errorf("%q is not an imported package alias in %s",
			alias.Name, sc.pkg.fset.Position(sel.Pos()))
	}
	if importPath != appModule && !strings.HasPrefix(importPath, appModule+"/") {
		return nil, scope{}, fmt.Errorf("cannot resolve %s.%s: %q is outside %s, and this script only "+
			"follows references within the app module", alias.Name, sel.Sel.Name, importPath, appModule)
	}
	subpath := strings.TrimPrefix(importPath, appModule)
	subpath = strings.TrimPrefix(subpath, "/")
	targetDir := filepath.Join(r.appRoot, subpath)
	target, err := r.packageAt(targetDir)
	if err != nil {
		return nil, scope{}, fmt.Errorf("resolving %s.%s: %w", alias.Name, sel.Sel.Name, err)
	}
	def, ok := target.consts[sel.Sel.Name]
	if !ok {
		return nil, scope{}, fmt.Errorf("no top-level const/var named %q in package %q", sel.Sel.Name, importPath)
	}
	return def.expr, scope{pkg: target, file: def.file}, nil
}

// resolveString evaluates an expression mcpserver could plausibly use for a tool's name or
// description: a string literal, a "+"-concatenation of them (the pattern every multi-line
// description in mcpserver uses), a reference to a package-level const/var holding the same
// (locally or in another package within this module), or a strconv.Itoa call wrapping a resolvable
// integer -- the one place a description interpolates a number. It deliberately implements only
// this narrow subset rather than reaching for go/types: the tool metadata never needs anything
// richer, and go/types would drag in the module-compiles requirement this script exists to avoid.
func (r *resolver) resolveString(expr ast.Expr, sc scope, seen map[string]bool) (string, error) {
	switch e := expr.(type) {
	case *ast.BasicLit:
		if e.Kind != token.STRING {
			return "", fmt.Errorf("expected a string literal, got %s", e.Kind)
		}
		return strconv.Unquote(e.Value)
	case *ast.BinaryExpr:
		if e.Op != token.ADD {
			return "", fmt.Errorf("unsupported operator %s in string expression", e.Op)
		}
		left, err := r.resolveString(e.X, sc, seen)
		if err != nil {
			return "", err
		}
		right, err := r.resolveString(e.Y, sc, seen)
		if err != nil {
			return "", err
		}
		return left + right, nil
	case *ast.Ident:
		if seen[e.Name] {
			return "", fmt.Errorf("cycle resolving constant %q", e.Name)
		}
		def, ok := sc.pkg.consts[e.Name]
		if !ok {
			return "", fmt.Errorf("no top-level const/var named %q in this package", e.Name)
		}
		seen[e.Name] = true
		return r.resolveString(def.expr, scope{pkg: sc.pkg, file: def.file}, seen)
	case *ast.ParenExpr:
		return r.resolveString(e.X, sc, seen)
	case *ast.SelectorExpr:
		def, target, err := r.resolveCrossPackage(e, sc)
		if err != nil {
			return "", err
		}
		return r.resolveString(def, target, map[string]bool{})
	case *ast.CallExpr:
		sel, ok := e.Fun.(*ast.SelectorExpr)
		if !ok {
			return "", fmt.Errorf("unsupported function call in string expression: %s", describeCall(e))
		}
		pkgAlias, ok := sel.X.(*ast.Ident)
		if !ok || pkgAlias.Name != "strconv" || sel.Sel.Name != "Itoa" {
			return "", fmt.Errorf("unsupported function call in string expression: %s", describeCall(e))
		}
		if len(e.Args) != 1 {
			return "", fmt.Errorf("strconv.Itoa call has %d arguments, expected 1", len(e.Args))
		}
		n, err := r.resolveInt(e.Args[0], sc, map[string]bool{})
		if err != nil {
			return "", fmt.Errorf("resolving strconv.Itoa argument: %w", err)
		}
		return strconv.Itoa(n), nil
	default:
		return "", fmt.Errorf("unsupported expression type %T in string expression", expr)
	}
}

// resolveInt evaluates an integer constant expression: a literal, basic arithmetic over such
// expressions (as in a millisecond constant divided down to seconds), or a reference to a
// package-level const/var (locally or cross-package) holding the same. Used only to resolve the
// argument of a strconv.Itoa call embedded in a description.
func (r *resolver) resolveInt(expr ast.Expr, sc scope, seen map[string]bool) (int, error) {
	switch e := expr.(type) {
	case *ast.BasicLit:
		if e.Kind != token.INT {
			return 0, fmt.Errorf("expected an integer literal, got %s", e.Kind)
		}
		return strconv.Atoi(e.Value)
	case *ast.BinaryExpr:
		left, err := r.resolveInt(e.X, sc, seen)
		if err != nil {
			return 0, err
		}
		right, err := r.resolveInt(e.Y, sc, seen)
		if err != nil {
			return 0, err
		}
		switch e.Op {
		case token.ADD:
			return left + right, nil
		case token.SUB:
			return left - right, nil
		case token.MUL:
			return left * right, nil
		case token.QUO:
			if right == 0 {
				return 0, fmt.Errorf("division by zero")
			}
			return left / right, nil
		case token.REM:
			if right == 0 {
				return 0, fmt.Errorf("division by zero")
			}
			return left % right, nil
		default:
			return 0, fmt.Errorf("unsupported operator %s in integer expression", e.Op)
		}
	case *ast.Ident:
		if seen[e.Name] {
			return 0, fmt.Errorf("cycle resolving constant %q", e.Name)
		}
		def, ok := sc.pkg.consts[e.Name]
		if !ok {
			return 0, fmt.Errorf("no top-level const/var named %q in this package", e.Name)
		}
		seen[e.Name] = true
		return r.resolveInt(def.expr, scope{pkg: sc.pkg, file: def.file}, seen)
	case *ast.ParenExpr:
		return r.resolveInt(e.X, sc, seen)
	case *ast.SelectorExpr:
		def, target, err := r.resolveCrossPackage(e, sc)
		if err != nil {
			return 0, err
		}
		return r.resolveInt(def, target, map[string]bool{})
	default:
		return 0, fmt.Errorf("unsupported expression type %T in integer expression", expr)
	}
}

func resolveBool(expr ast.Expr) (bool, error) {
	id, ok := expr.(*ast.Ident)
	if !ok {
		return false, fmt.Errorf("expected a true/false literal, got %T", expr)
	}
	switch id.Name {
	case "true":
		return true, nil
	case "false":
		return false, nil
	default:
		return false, fmt.Errorf("expected a true/false literal, got identifier %q", id.Name)
	}
}

func buildConstTable(files []*ast.File) map[string]constDecl {
	table := map[string]constDecl{}
	for _, f := range files {
		for _, decl := range f.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || (gen.Tok != token.CONST && gen.Tok != token.VAR) {
				continue
			}
			for _, spec := range gen.Specs {
				vs, ok := spec.(*ast.ValueSpec)
				if !ok {
					continue
				}
				for i, name := range vs.Names {
					if i < len(vs.Values) {
						table[name.Name] = constDecl{expr: vs.Values[i], file: f}
					}
				}
			}
		}
	}
	return table
}

// buildImportTable maps one file's own import aliases to their import paths. This is deliberately
// per file, not merged across a package: see the scope doc comment for why a package-wide table
// would be unsound.
func buildImportTable(f *ast.File) map[string]string {
	table := map[string]string{}
	for _, imp := range f.Imports {
		path, err := strconv.Unquote(imp.Path.Value)
		if err != nil {
			continue
		}
		var alias string
		if imp.Name != nil {
			alias = imp.Name.Name
		} else if i := strings.LastIndex(path, "/"); i >= 0 {
			alias = path[i+1:]
		} else {
			alias = path
		}
		table[alias] = path
	}
	return table
}

func describeCall(e *ast.CallExpr) string {
	if sel, ok := e.Fun.(*ast.SelectorExpr); ok {
		if pkg, ok := sel.X.(*ast.Ident); ok {
			return pkg.Name + "." + sel.Sel.Name + "(...)"
		}
	}
	if id, ok := e.Fun.(*ast.Ident); ok {
		return id.Name + "(...)"
	}
	return fmt.Sprintf("%T(...)", e.Fun)
}

// writeTable renders tools as the same Markdown-table shape the generated SDK method tables use
// (static/include/**/apis/generated/*-table.md), minus that convention's leading
// `<!-- prettier-ignore -->` comment: prettier-lint.yml only ever checks docs/**/*.md, so the
// comment does nothing in CI, and unlike the SDK tables (which are link-only in llms.txt), this one
// is inlined into llms-full.txt in full, so a stray comment here is more exposed to that page's
// actual audience than the convention it would have copied. Its content is mcpserver's own tool
// descriptions, written by app engineers for a different audience under a different style guide, so
// this repo's vale check is configured (in .github/workflows/vale-lint.yml, via the vale-action's
// `glob` input) to skip this generated path entirely rather than hold it to viam-docs prose rules --
// see CLAUDE.md's "Generated MCP server reference" section for why that's a CI-config exclusion and
// not an earlier approach this file used, in-document `<!-- vale off/on -->` markers: those worked
// for CI, but the table is inlined verbatim into this page's Markdown mirror and into llms-full.txt
// (see data/llms_pages.yaml), so the markers were served to every reader of either as literal
// visible text -- exactly the audience (AI agents reading llms-full.txt) this table exists for.
func writeTable(path string, tools []tool) error {
	var b strings.Builder
	b.WriteString("| Tool | Category | Description |\n")
	b.WriteString("| ---- | -------- | ----------- |\n")
	for _, t := range tools {
		b.WriteString(fmt.Sprintf("| `%s` | %s | %s |\n", t.Name, t.Category, escapeCell(linkifyURLs(t.Description))))
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("creating output directory: %w", err)
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}

func escapeCell(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}

var bareURLPattern = regexp.MustCompile(`https?://\S+`)

// urlLabels gives a few known URLs descriptive link text, curated by hand -- the generator has no
// reliable way to invent good link text for an arbitrary URL a future tool description might
// mention, and inventing bad text would be worse than not linking at all. This is the same shape as
// this repo's SDK-generated-docs proto description overrides (static/include/.../overrides/protos):
// a small hand-maintained mapping with a safe default for anything missing from it, rather than a
// hard requirement that fails the build. Add an entry here when a PR comment or a new tool
// description makes a URL worth linking.
var urlLabels = map[string]string{
	"https://docs.viam.com/reference/apis/":                      "Viam API reference",
	"https://docs.viam.com/operate/mobility/orientation-vector/": "orientation vector",
}

// linkifyURLs turns a bare URL into a proper Markdown link when urlLabels has descriptive text for
// it, and into a code span otherwise. Either way, the URL never reaches the page as a bare
// autolinked link: this site's render-link.html render hook fails any link whose visible text
// contains "https" (a descriptive-link-text check), and Goldmark's autolink/linkify extension turns
// a bare URL into exactly that kind of link. The check is on the link's visible text, not its
// destination, so a real `[label](url)` link passes cleanly -- confirmed with a local Hugo build --
// as long as the label itself doesn't contain "https", "www", or a bare "here".
func linkifyURLs(s string) string {
	return bareURLPattern.ReplaceAllStringFunc(s, func(url string) string {
		trailing := ""
		for len(url) > 0 && strings.ContainsRune(").,;:", rune(url[len(url)-1])) {
			trailing = string(url[len(url)-1]) + trailing
			url = url[:len(url)-1]
		}
		if label, ok := urlLabels[url]; ok {
			return "[" + label + "](" + url + ")" + trailing
		}
		return "`" + url + "`" + trailing
	})
}
