name: SDK method coverage

concurrency:
  group: pullrequest-untrusted-coverage-${{ github.event.number }}
  cancel-in-progress: true

on:
  schedule:
    # 10am UTC on weekdays
    - cron: '0 10 * * 3'
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  method-coverage:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true # Fetch Hugo themes
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
      - run: pip install beautifulsoup4 markdownify argparse

      - name: Run Coverage test
        run: make coveragetest
      - name: Report failure
        if: failure()
        uses: ./.github/actions/report-ci-failure
        with:
          job-name: SDK method coverage
