name: Pull Request Update

concurrency:
  group: pullrequest-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    branches: [ 'main' ]
    types: [ 'opened', 'reopened', 'synchronize' ]

# To test workflow updates you need to work in a branch directly on viamrobotics/docs
# and tag your working branch instead of @main in any viamrobotics/docs "uses" below.
# Don't forget to tag back to @main before merge.

jobs:
  gotest:
    uses: viamrobotics/docs/.github/workflows/pr-deploy-and-comment.yml