name: Test Code Samples

concurrency:
  group: pullrequest-untrusted-code-snippets-python-${{ github.event.number }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - 'static/include/examples/**'
      - '.github/workflows/test-code-snippets-python.yml'
  schedule:
    # Run every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  test-code-samples:
    runs-on: ubuntu-latest
    # Allow trusted PRs and other events
    if: github.repository_owner == 'viamrobotics'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Start viam-server in background
      run: |

        # Start viam-server in background and save PID
        sudo curl -H "key_id:1030f25a-f4f2-4872-9762-e33fa1e0444d" -H "key:$TEST_MACHINE_KEY" "https://app.viam.com/api/json1/config?id=deb8782c-7b48-4d35-812d-2caa94b61f77&client=true" -o /etc/viam.json
        curl https://storage.googleapis.com/packages.viam.com/apps/viam-server/viam-server-stable-aarch64.AppImage -o viam-server && chmod 755 viam-server && sudo ./viam-server &
        VIAM_PID=$!
        echo "VIAM_PID=$VIAM_PID" >> $GITHUB_ENV
        echo "Started viam-server with PID: $VIAM_PID"

        # Wait a moment for it to start
        sleep 5

        # Check if it's running
        if ps -p $VIAM_PID > /dev/null; then
          echo "viam-server is running with PID: $VIAM_PID"
        else
          echo "Failed to start viam-server"
          exit 1
        fi
      env:
        VIAM_API_KEY_ID: ${{ secrets.VIAM_API_KEY_ID }}
        VIAM_API_KEY: ${{ secrets.VIAM_API_KEY }}
        VIAM_PART_ID: "824b6570-7b1d-4622-a19d-37c472dba467"
        TEST_MACHINE_KEY: ${{ secrets.TEST_MACHINE_KEY }}

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install viam-sdk
        pip install asyncio
        pip install pytest
        pip install pytest-asyncio

    - name: Find and list Python files
      run: |
        echo "Found Python files in examples directory:"
        find static/include/examples -name "*.py" -type f | sort

    - name: Debug environment variables
      run: |
        echo "VIAM_API_KEY: ${#VIAM_API_KEY}"
        echo "VIAM_API_KEY_ID: ${#VIAM_API_KEY_ID}"
        echo "TEST_ORG_ID: ${#TEST_ORG_ID}"
      env:
        VIAM_API_KEY: ${{ secrets.VIAM_API_KEY }}
        VIAM_API_KEY_ID: ${{ secrets.VIAM_API_KEY_ID }}
        TEST_ORG_ID: ${{ secrets.TEST_ORG_ID }}

    - name: Test Python code samples
      if: github.repository_owner == 'viamrobotics'
      run: |
        echo "TEST_ORG_ID: $TEST_ORG_ID"

        # Find all Python files in the examples directory
        python_files=($(find static/include/examples -name "*.py" -type f | xargs))

        # Initialize counters
        total_files=0
        passed_files=0
        failed_files=0

        echo "Starting to test Python code samples..."
        echo "========================================"

        for file in "${python_files[@]}"; do
          echo "Testing: $file"
          total_files=$((total_files + 1))

          # Run the test with environment variables explicitly passed
          if VIAM_API_KEY="$VIAM_API_KEY" VIAM_API_KEY_ID="$VIAM_API_KEY_ID" TEST_ORG_ID="$TEST_ORG_ID" python "$file"; then
            passed_files=$((passed_files + 1))
            echo "✅ PASSED: $file"
          else
            failed_files=$((failed_files + 1))
            echo "❌ FAILED: $file"
          fi

          echo "----------------------------------------"
        done

        # Summary
        echo "========================================"
        echo "TEST SUMMARY:"
        echo "Total files tested: $total_files"
        echo "Passed: $passed_files"
        echo "Failed: $failed_files"
        echo "Skipped: $((total_files - passed_files - failed_files))"

        # Save results for later use
        echo "total=$total_files" >> $GITHUB_OUTPUT
        echo "passed=$passed_files" >> $GITHUB_OUTPUT
        echo "failed=$failed_files" >> $GITHUB_OUTPUT

        # Exit with failure if any tests failed
        if [ $failed_files -gt 0 ]; then
          exit 1
        fi
      env:
        VIAM_API_KEY: ${{ secrets.VIAM_API_KEY }}
        VIAM_API_KEY_ID: ${{ secrets.VIAM_API_KEY_ID }}
        TEST_ORG_ID: ${{ secrets.TEST_ORG_ID }}

    - name: Stop viam-server
      if: always()  # This ensures cleanup runs even if tests fail
      run: |
        if [ ! -z "$VIAM_PID" ]; then
          echo "Stopping viam-server with PID: $VIAM_PID"
          sudo kill $VIAM_PID 2>/dev/null || true

          # Wait for it to stop gracefully
          for i in {1..10}; do
            if ! ps -p $VIAM_PID > /dev/null 2>&1; then
              echo "viam-server stopped gracefully"
              break
            fi
            sleep 1
          done

          # Force kill if still running
          if ps -p $VIAM_PID > /dev/null 2>&1; then
            echo "Force killing viam-server"
            sudo kill -9 $VIAM_PID 2>/dev/null || true
          fi
        else
          echo "No viam-server PID found"
        fi

    - name: Create Jira ticket
      if: failure() && github.event_name == 'schedule'
      id: create
      uses: atlassian/gajira-create@v3
      env:
        GITHUB_RUN_ID: ${{ github.run_id }}
      with:
        project: DOCS
        issuetype: Task
        summary: Code Sample Tests Failed - Scheduled Run
        description: |
          Code sample tests failed during scheduled run.

          **Run Details:**
          - Run ID: ${{ github.run_id }}
          - Repository: ${{ github.repository }}
          - Branch: ${{ github.ref }}
          - Commit: ${{ github.sha }}
          - Triggered by: Scheduled run

          **Test Results:**
          - Total files tested: ${{ steps.test-code-samples.outputs.total }}
          - Passed: ${{ steps.test-code-samples.outputs.passed }}
          - Failed: ${{ steps.test-code-samples.outputs.failed }}

          For more details, see: https://github.com/viamrobotics/docs/actions/runs/${{ github.run_id }}
    - name: Log created Jira issue
      if: failure() && github.event_name == 'schedule'
      run: echo "Issue ${{ steps.create.outputs.issue }} was created for scheduled run failure"
